export const SEMIBOLD = '600'
export const MEDIUM = '500'
export const REGULAR = '400'
export const SM = 'sm'
export const MD = 'md'
export const LG = 'lg'
export const MEDIA_LG = '(min-width: 1360px)'
export const MEDIA_MD = '(min-width: 736px) and (max-width: 1359.98px)'
export const MEDIA_SM = '(max-width: 735.98px)'
export const COLUMNS_LG_WIDTH = 32
export const COLUMNS_MD_WIDTH = 32
export const COLUMNS_SM_WIDTH = 16
export const MONTHS = 12
export const DEX_RADIX = 10
export const HEX_RADIX = 16